#!/bin/bash
for i in 512 1024 2048 4096 8192 16384 32768 65536 131072 262144; do 
	echo "$i";
	python process.py $i /tmp/10MB &
	python process.py $i /tmp/10MB &
	python process.py $i /tmp/10MB &
	python process.py $i /tmp/10MB &
	wait
done
